name: bibliopolium
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localizations
  flutter_localizations:
    sdk: flutter    
  # Gerenciador de estados
  get: ^4.6.1
  # LocalStorage
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  # Firebase
  firebase_core: ^1.13.1  
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  # Google
  google_sign_in: ^5.2.4
  google_fonts: ^2.3.1
  # outros
  uuid: ^3.0.6
  validatorless: ^1.2.1
  date_picker_timeline: ^1.2.3
  intl: ^0.17.0


  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
